[package]
name = "kodept-ast-nodes"
version = "0.2.5"
edition = "2021"

[lints]
workspace = true

[dependencies]
bevy_ecs.workspace = true
kodept-ast = { path = "../kodept-ast" }
kodept-rlt = { path = "../kodept-rlt" }

[features]
defalt = []
parallel = ["kodept-ast/parallel", "bevy_ecs/multi_threaded", "bevy_ecs/async_executor"]
