[workspace]
resolver = "3"
members = [
    "crates/kodept-core"
    , "crates/kodept-parse"
    , "crates/kodept-inference"
    , "crates/kodept-ast"
    , "crates/kodept-report"
    , "crates/kodept-interning"
    , "crates/kodept-ast-nodes"
    , "crates/kodept-rlt"
    , "crates/kodept-frontend"
    , "crates/kodept-systems"
    , "crates/kodept-cli"
    , "crates/kodept-report-macros"
    , "crates/kodept-ir"
    , "bin/kodept-ast-visualizer"
    , "bin/kodept-check"
    , "crates/kodept-ecs"]

[workspace.package]
edition = "2024"
rust-version = "1.89.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
tracing = "0.1.40"

[workspace.dependencies.derive_more]
version = "2.0.1"
features = [
    "into", "from",
    "display", "error",
    "try_into", "try_from",
    "constructor"
]

[workspace.lints]
clippy.suspicious = "deny"
clippy.correctness = "deny"
clippy.complexity = "warn"
clippy.style = "warn"
clippy.perf = "warn"
rust.unsafe_code = "deny"
rust.unreachable_pub = "warn"

[profile.test.package.proptest]
opt-level = 3

[profile.test.package.rand_chacha]
opt-level = 3

[profile.profiler]
debug = true
lto = "thin"
strip = false
inherits = "release"

[profile.bench]
opt-level = 3
lto = false

[profile.release]
opt-level = 3
lto = "fat"
panic = 'unwind'
strip = true
codegen-units = 1
rpath = true

[profile.light]
inherits = "release"
opt-level = 2
lto = false

[profile.dev]
opt-level = 0
debug = true
panic = 'unwind'
# kodept-parse produces *a lot* of debug info
split-debuginfo = "packed"
rpath = true
