[package]
name = "kodept"
version = "0.2.3"
edition = "2021"
authors = ["Владимир Никитин <potyras85@mail.ru>"]
description = "Simple compiler with dependent types support in mind"
repository = "https://github.com/ITesserakt/Kodept/"
categories = ["compilers"]
license = "Apache-2.0"
rust-version = "1.76.0"

[workspace]
resolver = "2"
members = [
    ".",
    "crates/kodept-core",
    "crates/kodept-parse",
    "crates/kodept-inference",
    "crates/kodept-ast",
    "crates/kodept-macros",
    "crates/kodept-interpret",
    "crates/kodept-ir",
    "crates/kodept-interning",
    "crates/kodept-ast-nodes"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
bevy_ecs = { version = "0.15.1", default-features = false }
thiserror = "2.0"
extend = "1.2"
itertools = "0.13"
nonempty-collections = "0.2.9"
tracing = "0.1.40"

[workspace.dependencies.derive_more]
version = "1.0.0"
features = ["display", "into", "from", "deref", "deref_mut", "constructor", "try_into", "is_variant", "unwrap"]

[workspace.lints]
clippy.suspicious = "deny"
clippy.correctness = "deny"
clippy.complexity = "warn"
clippy.style = "warn"
clippy.perf = "warn"
rust.unsafe_code = "deny"
rust.unreachable_pub = "warn"

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive", "env"] }
ctrlc = { version = "3.4.4", optional = true }
codespan-reporting = "0.11.1"
derive_more.workspace = true
dhat = { version = "0.3", optional = true }
gag = { version = "1.0.0", optional = true }
itertools.workspace = true
memmap2 = { version = "0.9.5", features = ["stable_deref_trait"] }
rayon = { version = "1.10.0", optional = true }
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3.17", default-features = false, features = ["fmt", "ansi"] }
yoke = "0.7.4"

[dependencies.kodept-core]
path = "crates/kodept-core"

[dependencies.kodept-parse]
path = "crates/kodept-parse"
version = "0.3"

[dependencies.kodept-ast]
path = "crates/kodept-ast"

[dependencies.kodept-macros]
path = "crates/kodept-macros"

[dependencies.kodept-interning]
path = "crates/kodept-interning"
optional = true

[dependencies.kodept-ast-nodes]
path = "crates/kodept-ast-nodes"

[dev-dependencies]
tempfile = "3.7.0"

[features]
profiler = ["dep:dhat", "dep:ctrlc"]
parallel = ["dep:rayon", "kodept-parse/parallel", "kodept-ast/parallel"]
trace = ["dep:gag", "kodept-parse/trace"]
interning = ["dep:kodept-interning", "kodept-ast/interning"]

[profile.profiler]
debug = true
lto = "thin"
strip = false
inherits = "release"

[profile.bench]
opt-level = 3

[profile.release]
opt-level = 3
lto = "fat"
panic = 'unwind'
strip = true

[profile.dev]
opt-level = 0
debug = true
panic = 'unwind'
