[package]
name = "kodept"
version = "0.2.3"
edition.workspace = true
rust-version.workspace = true
authors = ["Владимир Никитин <potyras85@mail.ru>"]
description = "Simple compiler with dependent types support in mind"
repository = "https://github.com/ITesserakt/Kodept/"
categories = ["compilers"]
license = "Apache-2.0"

[workspace]
resolver = "3"
members = [
    "."
    , "crates/kodept-core"
    , "crates/kodept-parse"
    , "crates/kodept-inference"
    , "crates/kodept-ast"
    , "crates/kodept-report"
    # , "crates/kodept-ir"
    , "crates/kodept-interning"
    , "crates/kodept-ast-nodes"
    , "crates/kodept-rlt"
    , "crates/kodept-frontend"
    , "crates/kodept-systems"]

[workspace.package]
edition = "2024"
rust-version = "1.88.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
bevy_ecs = { version = "0.17.2", default-features = false }
bevy_tasks = { version = "0.17.2", default-features = false, features = ["async_executor"] }
tracing = "0.1.40"

[workspace.dependencies.derive_more]
version = "2.0.1"
features = [
    "into", "from",
    "display", "error",
    "try_into", "try_from",
    "constructor"
]

[workspace.lints]
clippy.suspicious = "deny"
clippy.correctness = "deny"
clippy.complexity = "warn"
clippy.style = "warn"
clippy.perf = "warn"
rust.unsafe_code = "deny"
rust.unreachable_pub = "warn"

[dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
tracing.workspace = true
tracing-subscriber = { version = "0.3.17", default-features = false, features = ["fmt", "ansi"] }

dhat = { version = "0.3", optional = true }
rayon = { version = "1.10.0", optional = true }

kodept-frontend = { path = "crates/kodept-frontend" }
kodept-systems = { path = "crates/kodept-systems" }
kodept-report = { path = "crates/kodept-report" }

kodept-interning = { path = "crates/kodept-interning", optional = true }

[features]
default = []
profiler = ["dep:dhat"]
interning = ["dep:kodept-interning", "kodept-interning/code_holder", "kodept-interning/metrics"]
parallel = [
    "dep:rayon"
    , "kodept-systems/parallel"
]

[profile.test.package.proptest]
opt-level = 3

[profile.test.package.rand_chacha]
opt-level = 3

[profile.profiler]
debug = true
lto = "thin"
strip = false
inherits = "release"

[profile.bench]
opt-level = 3
lto = false

[profile.release]
opt-level = 3
lto = "fat"
panic = 'unwind'
strip = true
codegen-units = 1

[profile.light]
inherits = "release"
opt-level = 2
lto = false

[profile.dev]
opt-level = 0
debug = true
panic = 'unwind'
# kodept-parse produces *a lot* of debug info
split-debuginfo = "packed"
