flowchart TD
;
    A[kodept-core];
    B[kodept-ast];
    C[kodept-parse];
    D[kodept-macros];
    E[kodept-inference];
    F[kodept-interpret];
    G[kodept];

    IN[/Исходный код/]
    OUT[/Диагностики/]

    IN -.-> C;
    C -.-> B;

    A --> B;
    A --> D;
    D --> F;
    B --> F;
    B -.-> F;
    A --> F;
    A --> C;
    A --> G;
    C --> G;
    B --> G;
    B --> D;
    D --> G;
    E --> F;
    F --> G;

    F -.-> OUT;
