stateDiagram-v2
    Err: Диагностики
    Le: Лексический анализатор
    Sy: Синтаксический анализатор
    Se: Семантический анализатор
    IR: Генератор промежуточного представления
    Ge: Генератор машинного кода

    [*] --> Le: исходный код программы
    Le --> Sy: поток токенов
    Sy --> Se: AST
    Sy --> IR: AST
    Se --> IR
    IR --> Ge: промежуточное представление
    Ge --> [*]: исполняемый файл

    Se --> Err
    Sy --> Err
    Le --> Err

    Err --> [*]: ошибка компиляции
