[package]
name = "kodept-macros"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
size-of = ["dep:size-of"]

[dependencies]
kodept-ast = { path = "../kodept-ast", version = "0.1" }
kodept-core = { path = "../kodept-core", version = "0.2" }

visita = { path = "../visita", version = "0.3" }

codespan = "0.11.1"
codespan-reporting = "0.11.1"
derive_more = { version = "0.99", features = ["try_into"] }
size-of = { version = "0.1.5", optional = true }
tracing = "0.1.37"
