@startuml
'https://plantuml.com/state-diagram

state "Лексический анализ" as Le
Le: исходный код программы
state "Синтаксический анализ" as Sy
Sy: поток токенов
state "Семантический анализ" as Se
Se: абстрактное синтаксическое \n дерево
state "Генерация промежуточного \n представления" as IR
IR: символьные таблицы
state "Генерация машинного кода" as Ge
Ge: промежуточное представление

[*] --> Le
Le --> Sy
Sy --> Se
Sy --> IR
Se --> IR
IR --> Ge
Ge --> [*]

@enduml