@startwbs
'https://plantuml.com/wbs-diagram

* =0
**:=1
    //Определения://
    ""Bool, compose"";

***:=12
    //Определения://
    ""True, False"";

***:=2
    //Определения://
    ""f, g"";
****:=5
    //Определения://
    ""x"";

**:=15
    //Определения://
    ""Int"";

@endwbs