[package]
name = "kodept-ast"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
serde = ["dep:serde"]
size-of = ["dep:size-of"]

[dependencies]
kodept-core = { path = "../kodept-core" }

visita = { path = "../visita", version = "0.3" }

derive_more = { version = "0.99", features = ["from", "try_into", "constructor"] }
serde = { version = "1.0.188", optional = true, features = ["derive"] }
size-of = { version = "0.1.5", optional = true }
tracing = "0.1.37"
paste = "1.0.14"
ghost-cell = { version = "0.2.4", features = ["experimental-ghost-cursor"] }
static-rc = "0.6.1"
typed-arena = "2.0.2"
fixedbitset = "0.4.2"