[package]
name = "kodept-ast"
version = "0.7.2"
edition = "2021"
authors = ["Владимир Никитин <potyras85@mail.ru>"]
description = "Simple compiler with dependent types support in mind"
repository = "https://github.com/ITesserakt/Kodept/"
categories = ["compilers"]
license = "Apache-2.0"
rust-version = "1.80.0"

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
parallel = ["dep:rayon", "bevy_ecs/multi_threaded"]
reflect = ["bevy_ecs/bevy_reflect"]

[dependencies]
bevy_ecs.workspace = true
derive_more.workspace = true
smallvec = "1.13.2"

rayon = { version = "1.10.0", optional = true }

[dependencies.kodept-core]
path = "../kodept-core"

[dependencies.kodept-rlt]
path = "../kodept-rlt"
