[package]
name = "kodept-ast"
version = "0.7.4"
authors = ["Владимир Никитин <potyras85@mail.ru>"]
description = "Simple compiler with dependent types support in mind"
repository = "https://github.com/ITesserakt/Kodept/"
categories = ["compilers"]
license = "Apache-2.0"
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
parallel = ["dep:rayon", "bevy_ecs/multi_threaded", "bevy_ecs/async_executor"]
debug = ["bevy_utils/debug"]
reflection = ["debug"]

[dependencies]
bevy_ecs.workspace = true
derive_more.workspace = true
smallvec = "1.15.1"

bevy_utils = { workspace = true, optional = true }
rayon = { version = "1.11", optional = true }

[dependencies.kodept-core]
path = "../kodept-core"

[dependencies.kodept-rlt]
path = "../kodept-rlt"
