[package]
name = "kodept-ast"
version = "0.2.2"
edition = "2021"
authors = ["Владимир Никитин <potyras85@mail.ru>"]
description = "Simple compiler with dependent types support in mind"
repository = "https://github.com/ITesserakt/Kodept/"
categories = ["compilers"]
license = "Apache-2.0"
rust-version = "1.74.0"

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
serde = ["dep:serde"]
size-of = ["dep:size-of"]

[dependencies]
derive_more.workspace = true
serde = { version = "1.0.188", optional = true, features = ["derive"] }
size-of = { version = "0.1.5", optional = true }
tracing = "0.1.37"
paste = "1.0.14"
qcell = "0.5.4"
petgraph = { version = "0.6.4", features = ["stable_graph"] }

[dependencies.kodept-core]
path = "../kodept-core"
version = "0.2"

[dev-dependencies]
rstest = "0.18.2"