@startuml
'https://plantuml.com/state-diagram

scale 0.9

state Frontend {
    state "Лексический анализ" as Le

    state "Синтаксический анализ" as Sy
}

state "Middle-end" as M {
    state "Семантический анализ" as Se

    state "Генерация промежуточного представления" as IR
}

state Backend {
    state "Генерация машинного кода" as Ge
}

[*] -right-> Le:исходный код
Le --> Sy: поток токенов
Sy --> Se: AST
Sy --> IR: AST
Se --> IR: символьные таблицы
IR --> Ge: промежуточное представление
Ge --> [*]: объектный файл

@enduml