@startwbs
'https://plantuml.com/wbs-diagram

* =[0]
**:=[1] Testing
    //Определения://
    ""Bool, compose"";

***:=[13] Bool
    //Определения://
    ""True, False"";

***:=[3] compose
    //Определения://
    ""f, g"";
****:=[6]
    //Определения://
    ""x"";

**:=[16] Testing2
    //Определения://
    ""Int"";

@endwbs