@startuml
'https://plantuml.com/use-case-diagram

:Пользователь: as U
:Разработчик: as D

(Обработать файл) as (Compile)
(Сохранить \n структуру \n AST в файл) as (Save)
(Получить AST) as (AST)
(Проверить семантику) as (Semantics)

U --> (Compile)

(Compile) .right.> (AST): включает
(Save) ..> (AST): включает
(Compile) ..> (Semantics): включает


D -left-|> U
D --> (Save)

@enduml