@startuml
'https://plantuml.com/use-case-diagram

left to right direction

:Пользователь: as U
:Разработчик: as D

rectangle "Прототип компилятора" {
    usecase "Обработать файл" as Compile
    usecase "Сохранить \n структуру \n AST в файл" as Save
    usecase "Получить AST" as AST
    usecase "Проверить семантику" as Semantics
}

U --> Compile

D --> Save

D --left-|> U

Compile .left.> "включает" AST
Compile .right.> "включает" Semantics

Save .right.> "включает" AST

@enduml