flowchart TD;
    Start([Начало])
    Input[/"$$\mathcal{W}_c (\Gamma, e)~$$- входные данные"/]
    Set[["$$\mathcal{A}, \mathcal{C} \vdash e: \tau~$$"- правила вывода]]
    Check{"$$dom(\mathcal{A}) \subseteq dom(\Gamma)$$"}
    Error[Вывод сообщения об ошибке]
    End([Конец])
    Subst[["$$\mathcal{S} = solve(\mathcal{C} \cup (\mathcal{A} \preceq \Gamma))$$"]]
    Out[/"$$\mathcal{S}, \mathcal{S} \tau~$$- результат"/]

    Start --> Input
    Input --> Set

    Set --> Check
    Check -->|Нет| Error
    Error --> End

    Check -->|Да| Subst
    Subst --> Out
    Out --> End
