stateDiagram-v2
    A: 0
    B: 1
    C: 2
    D: 5
    E: 12
    F: 15

    A --> B
    B --> C
    C --> D
    C --> E
    A --> F

    note left of B: Определения - Bool и compose
    note right of C: Определения - f и g
    note left of D: Определения - x
    note left of E: Определения - True и False
    note left of F: Определения - Int