[package]
name = "kodept-parse"
version = "0.1.2"
edition = "2021"

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
size-of = ["dep:size-of", "kodept-core/size-of"]
enum-iter = ["dep:enum-iterator"]

[dependencies]
kodept-core = { path = "../kodept-core" }

derive_more.workspace = true
enum-iterator = { version = "1.4.1", optional = true }
extend = { workspace = true }
nom = { workspace = true }
nom-supreme = "0.8.0"
nonempty-collections = "0.1"
size-of = { optional = true, workspace = true }
thiserror = "1.0.44"

[dev-dependencies]
test-case = "3.2.1"
