[package]
name = "kodept-parse"
version = "0.3.2"
edition = "2021"
authors = ["Владимир Никитин <potyras85@mail.ru>"]
description = "Simple compiler with dependent types support in mind"
repository = "https://github.com/ITesserakt/Kodept/"
categories = ["compilers"]
license = "Apache-2.0"
rust-version = "1.77.0"

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
enum-iter = ["dep:enum-iterator"]
trace = ["peg/trace", "dep:gag"]
parallel = ["dep:rayon"]

[dependencies]
derive_more.workspace = true
itertools.workspace = true
nonempty-collections.workspace = true
thiserror.workspace = true

nom = "8.0.0"
peg = "0.8.3"
pest = "2.7.11"
faster-pest = "0.1.4"

enum-iterator = { version = "2.1.0", optional = true }
gag = { version = "1.0.0", optional = true }
rayon = { version = "1.10.0", optional = true }

[dependencies.kodept-core]
path = "../kodept-core"
version = "0.2"

[dependencies.kodept-rlt]
path = "../kodept-rlt"
version = "0.1"

[dev-dependencies]
rstest = "0.19.0"
criterion = "0.5.1"
similar-asserts = "1.5.0"

[[bench]]
name = "tokenizer"
harness = false
required-features = ["parallel"]

[[bench]]
name = "parser"
harness = false

[[test]]
name = "tokenizer"
required-features = ["parallel"]
