[package]
name = "kodept-parse"
version = "0.4.1"
authors = ["Владимир Никитин <potyras85@mail.ru>"]
description = "Simple compiler with dependent types support in mind"
repository = "https://github.com/ITesserakt/Kodept/"
categories = ["compilers"]
license = "Apache-2.0"
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
enum-iter = ["dep:enum-iterator"]
trace = ["peg/trace", "dep:gag"]
parallel = ["dep:rayon"]

[dependencies]
derive_more.workspace = true

peg = "0.8.5"

enum-iterator = { version = "2.1.0", optional = true }
gag = { version = "1.0.0", optional = true }
rayon = { version = "1.10.0", optional = true }

[dependencies.kodept-core]
path = "../kodept-core"

[dependencies.kodept-rlt]
path = "../kodept-rlt"

[dev-dependencies]
rstest = "0.26.1"
criterion = "0.7.0"
similar-asserts = "1.7.0"

[[bench]]
name = "tokenizer"
harness = false
required-features = ["parallel"]

[[bench]]
name = "parser"
harness = false

[[test]]
name = "tokenizer"
required-features = ["parallel"]
