[package]
name = "kodept-parse"
version = "0.1.4"
edition = "2021"
authors = ["Владимир Никитин <potyras85@mail.ru>"]
description = "Simple compiler with dependent types support in mind"
repository = "https://github.com/ITesserakt/Kodept/"
categories = ["compilers"]
license = "Apache-2.0"
rust-version = "1.74.0"

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
size-of = ["dep:size-of", "kodept-core/size-of"]
enum-iter = ["dep:enum-iterator"]

[dependencies]
derive_more.workspace = true
enum-iterator = { version = "1.4.1", optional = true }
extend = { workspace = true }
nom = { workspace = true }
nom-supreme = "0.8.0"
nonempty-collections = "0.1"
size-of = { optional = true, workspace = true }
thiserror = "1.0.44"

[dependencies.kodept-core]
path = "../kodept-core"
version = "0.2"

[dev-dependencies]
test-case = "3.2.1"
