[package]
name = "kodept-interaction"
version = "0.1.2"
edition.workspace = true
rust-version.workspace = true

[dependencies]
bevy_ecs.workspace = true
tracing.workspace = true

kodept-ast = { path = "../kodept-ast" }
kodept-ast-nodes = { path = "../kodept-ast-nodes" }
kodept-core = { path = "../kodept-core" }
kodept-inference = { path = "../kodept-inference" }
kodept-report = { path = "../kodept-report" }
kodept-rlt = { path = "../kodept-rlt" }

[dev-dependencies]
rstest = "0.24.0"

[lints]
workspace = true

[features]
default = []
parallel = ["bevy_ecs/multi_threaded", "kodept-ast-nodes/parallel", "kodept-ast/parallel"]
