[package]
name = "kodept-inference"
version = "0.2.8"
authors = ["Владимир Никитин <potyras85@mail.ru>"]
description = "Simple compiler with dependent types support in mind"
repository = "https://github.com/ITesserakt/Kodept/"
categories = ["compilers"]
license = "Apache-2.0"
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more.workspace = true
linked-hash-map = "0.5.6"
smallvec = "1.15.1"

kodept-interning = { version = "0.1", path = "../kodept-interning" }

[dev-dependencies]
proptest = "1.8.0"
proptest-derive = "0.6.0"