[package]
name = "kodept-qbe"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
derive_more.workspace = true
itertools.workspace = true
nonempty-collections.workspace = true
sealed = "0.6.0"
smallvec = "1.15.1"

[dev-dependencies]
similar-asserts = "1.5.0"

[lints]
workspace = true
