[package]
name = "kodept-qbe"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more.workspace = true
itertools.workspace = true
nonempty-collections.workspace = true
sealed = "0.5.0"
smallvec = "1.13.2"

[dev-dependencies]
similar-asserts = "1.5.0"

[lints]
workspace = true
