[package]
name = "kodept-rlt"
version = "0.2.2"
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
serde = ["dep:serde", "kodept-core/serde"]
arbitrary = ["kodept-core/arbitrary", "dep:proptest", "dep:proptest-derive"]

[dependencies]
derive_more.workspace = true
serde = { version = "1", features = ["derive"], optional = true }

kodept-core = { version = "0.4", path = "../kodept-core" }
proptest = { version = "1.8.0", optional = true }
proptest-derive = { version = "0.6.0", optional = true }
