[package]
name = "kodept-rlt"
version = "0.2.1"
edition = "2021"

[lints]
workspace = true

[features]
serde = ["dep:serde", "kodept-core/serde"]

[dependencies]
derive_more.workspace = true
serde = { version = "1", features = ["derive"], optional = true }

[dependencies.kodept-core]
path = "../kodept-core"
